from __future__ import annotations

import csv
import json
import math
import re
from pathlib import Path
from statistics import mean, stdev
from typing import Any

from .io import read_json, read_jsonl, write_json
from .schemas import DIMENSIONS, V2ScoreRecord


def _safe_artifact_name(value: str) -> str:
    return re.sub(r"[^A-Za-z0-9._-]", "_", value)


def _display_path(path: Path, root: Path) -> str:
    resolved = path.resolve()
    resolved_root = root.resolve()
    return str(resolved.relative_to(resolved_root)) if resolved.is_relative_to(resolved_root) else str(path)


def _write_csv(path: Path, rows: list[dict[str, Any]], fieldnames: list[str] | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if fieldnames is None:
        fields: list[str] = []
        for row in rows:
            for key in row:
                if key not in fields:
                    fields.append(key)
        fieldnames = fields
    with path.open("w", encoding="utf-8", newline="") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames, lineterminator="\n")
        writer.writeheader()
        for row in rows:
            writer.writerow({key: row.get(key, "") for key in fieldnames})


def _metric_rows(mapping: dict[str, Any], id_field: str) -> list[dict[str, Any]]:
    rows = []
    for key, value in sorted(mapping.items()):
        if isinstance(value, dict):
            row = {id_field: key}
            for metric, metric_value in value.items():
                if isinstance(metric_value, dict):
                    for subkey, subvalue in metric_value.items():
                        row[f"{metric}_{subkey}"] = subvalue
                else:
                    row[metric] = metric_value
            rows.append(row)
    return rows


def _overall_rows(analysis: dict[str, Any], run_id: str) -> list[dict[str, Any]]:
    overall = analysis.get("overall", {})
    paired = analysis.get("refusal", {}).get("paired_parity", {})
    quality = analysis.get("quality_non_refusal", {}).get("overall", {})
    return [
        {"run_id": run_id, "metric": "n_scores", "value": overall.get("n_scores")},
        {"run_id": run_id, "metric": "n_non_refusal", "value": overall.get("n_non_refusal")},
        {"run_id": run_id, "metric": "refusal_rate", "value": overall.get("refusal_rate")},
        {"run_id": run_id, "metric": "over_refusal_rate", "value": overall.get("over_refusal_rate")},
        {
            "run_id": run_id,
            "metric": "warranted_refusal_rate_among_refusals",
            "value": overall.get("warranted_refusal_rate_among_refusals"),
        },
        {"run_id": run_id, "metric": "one_sided_refusal_rate", "value": paired.get("one_sided_refusal_rate")},
        {"run_id": run_id, "metric": "one_sided_refusal_count", "value": paired.get("one_sided_refusal_count")},
        {"run_id": run_id, "metric": "mean_non_refusal_quality", "value": _mean_quality(quality)},
    ]


def _pct(value: Any) -> str:
    if not isinstance(value, (int, float)):
        return "--"
    return f"{value * 100:.1f}\\%"


def _tex_value(value: Any) -> str:
    if value is None:
        return "--"
    if isinstance(value, float):
        return f"{value:.3f}".rstrip("0").rstrip(".")
    return str(value)


def _write_numbers_tex(path: Path, summary: dict[str, Any]) -> None:
    baseline = summary.get("baseline", {})
    overall = baseline.get("overall", {})
    paired = baseline.get("paired_refusal", {})
    robustness = summary.get("judge_robustness", {})
    post = robustness.get("poststratified", {})
    frontier = summary.get("frontier", {}).get("overall", {})
    remediation = summary.get("remediation", {})
    regression = summary.get("regression_gate", {})
    human = summary.get("human_calibration", {})
    ablations = summary.get("policy_ablations", {})
    stress = summary.get("stress", {})
    lines = [
        "% Generated by adfe_runner build-paper-artifacts. Do not hand-edit.",
        f"\\newcommand{{\\BaselineRows}}{{{_tex_value(overall.get('n_scores'))}}}",
        f"\\newcommand{{\\BaselineNonrefusalRows}}{{{_tex_value(overall.get('n_non_refusal'))}}}",
        f"\\newcommand{{\\BaselineRefusalRate}}{{{_pct(overall.get('refusal_rate'))}}}",
        f"\\newcommand{{\\BaselineOverRefusalRate}}{{{_pct(overall.get('over_refusal_rate'))}}}",
        f"\\newcommand{{\\BaselineOneSidedPairs}}{{{_tex_value(paired.get('one_sided_refusal_count'))}}}",
        f"\\newcommand{{\\BaselinePairCount}}{{{_tex_value(paired.get('n_pairs'))}}}",
        f"\\newcommand{{\\BaselineOneSidedRate}}{{{_pct(paired.get('one_sided_refusal_rate'))}}}",
        f"\\newcommand{{\\JudgeSensitivityRows}}{{{_tex_value(robustness.get('n_common'))}}}",
        f"\\newcommand{{\\JudgeRefusalAgreement}}{{{_pct(robustness.get('refusal_agreement_rate'))}}}",
        f"\\newcommand{{\\JudgePostMismatch}}{{{_pct(post.get('refusal_mismatch_rate'))}}}",
        f"\\newcommand{{\\FrontierRows}}{{{_tex_value(frontier.get('n_scores'))}}}",
        f"\\newcommand{{\\FrontierRefusalRate}}{{{_pct(frontier.get('refusal_rate'))}}}",
        f"\\newcommand{{\\RemediationAvailable}}{{{'yes' if remediation.get('available') else 'no'}}}",
        f"\\newcommand{{\\RemediationRows}}{{{_tex_value(remediation.get('overall', {}).get('n_scores'))}}}",
        f"\\newcommand{{\\PolicyAblationArms}}{{{_tex_value(ablations.get('n_available'))}}}",
        f"\\newcommand{{\\StressAvailable}}{{{'yes' if stress.get('available') else 'no'}}}",
        f"\\newcommand{{\\RegressionGatePassed}}{{{'yes' if regression.get('passed') else 'no'}}}",
        f"\\newcommand{{\\HumanRatings}}{{{_tex_value(human.get('n_ratings'))}}}",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def _mean_quality(row: dict[str, Any]) -> float | None:
    values = [row.get(dim) for dim in DIMENSIONS if isinstance(row.get(dim), (int, float))]
    return round(mean(values), 4) if values else None


def _score_key(score: V2ScoreRecord) -> tuple[str, str, str, str]:
    return (score.model, score.role, score.agency_mode, score.prompt_id)


def _profile_fit(score: V2ScoreRecord) -> float:
    return mean(score.role_profile_scores[dim] for dim in DIMENSIONS)


def _quality_mean(score: V2ScoreRecord) -> float | None:
    if score.refusal:
        return None
    return mean(score.quality_scores[dim] for dim in DIMENSIONS)


def _over_refusal_value(score: V2ScoreRecord) -> float:
    return 1.0 if score.refusal and score.refusal_warranted is not True else 0.0


def _delta_summary(values: list[float]) -> dict[str, Any]:
    if not values:
        return {"n": 0, "mean_delta": None, "ci95_low": None, "ci95_high": None}
    avg = mean(values)
    if len(values) == 1:
        return {"n": 1, "mean_delta": round(avg, 4), "ci95_low": None, "ci95_high": None}
    se = stdev(values) / math.sqrt(len(values))
    return {
        "n": len(values),
        "mean_delta": round(avg, 4),
        "ci95_low": round(avg - 1.96 * se, 4),
        "ci95_high": round(avg + 1.96 * se, 4),
    }


def matched_remediation_deltas(baseline_scores: list[V2ScoreRecord], remediation_scores: list[V2ScoreRecord]) -> list[dict[str, Any]]:
    baseline_by_key = {_score_key(score): score for score in baseline_scores}
    remediation_by_key = {_score_key(score): score for score in remediation_scores}
    common = sorted(set(baseline_by_key) & set(remediation_by_key))
    metric_values: dict[str, list[float]] = {
        "refusal_rate": [],
        "over_refusal_rate": [],
        "role_profile_fit": [],
        "non_refusal_quality": [],
    }
    by_role: dict[str, dict[str, list[float]]] = {}
    for key in common:
        baseline = baseline_by_key[key]
        remediation = remediation_by_key[key]
        role = key[1]
        role_bucket = by_role.setdefault(role, {metric: [] for metric in metric_values})
        deltas = {
            "refusal_rate": float(remediation.refusal) - float(baseline.refusal),
            "over_refusal_rate": _over_refusal_value(remediation) - _over_refusal_value(baseline),
            "role_profile_fit": _profile_fit(remediation) - _profile_fit(baseline),
        }
        baseline_quality = _quality_mean(baseline)
        remediation_quality = _quality_mean(remediation)
        if baseline_quality is not None and remediation_quality is not None:
            deltas["non_refusal_quality"] = remediation_quality - baseline_quality
        for metric, value in deltas.items():
            metric_values[metric].append(value)
            role_bucket[metric].append(value)

    rows = [{"slice": "overall", "metric": metric, **_delta_summary(values)} for metric, values in metric_values.items()]
    for role, metrics in sorted(by_role.items()):
        for metric, values in metrics.items():
            rows.append({"slice": f"role:{role}", "metric": metric, **_delta_summary(values)})
    return rows


def _has_delta_observations(rows: list[dict[str, Any]]) -> bool:
    return any(isinstance(row.get("n"), int) and row["n"] > 0 for row in rows)


def _load_primary_scores(run_root: Path) -> list[V2ScoreRecord]:
    meta = read_json(run_root / "v2" / "meta.json")
    judge = meta.get("primary_judge")
    if not judge:
        return []
    return read_jsonl(run_root / "v2" / _safe_artifact_name(judge) / "scores.jsonl", V2ScoreRecord)


def _delta_rows_with_arm(
    baseline_scores: list[V2ScoreRecord],
    candidate_scores: list[V2ScoreRecord],
    *,
    arm: str,
) -> list[dict[str, Any]]:
    rows = matched_remediation_deltas(baseline_scores, candidate_scores)
    for row in rows:
        row["arm"] = arm
    return rows


def _flatten_regression_gate(result: dict[str, Any]) -> list[dict[str, Any]]:
    if not result:
        return []
    rows = [
        {"metric": "passed", "value": result.get("passed")},
        {"metric": "n_gate_keys", "value": result.get("n_gate_keys")},
        {"metric": "n_common", "value": result.get("n_common")},
        {"metric": "failures", "value": ";".join(result.get("failures", []))},
    ]
    for section in ("baseline", "candidate", "delta"):
        for metric, value in result.get(section, {}).items():
            if isinstance(value, dict):
                for submetric, subvalue in value.items():
                    rows.append({"metric": f"{section}.{metric}.{submetric}", "value": subvalue})
            else:
                rows.append({"metric": f"{section}.{metric}", "value": value})
    return rows


def _human_summary_rows(summary: dict[str, Any]) -> list[dict[str, Any]]:
    if not summary:
        return []
    rows = [
        {"section": "overall", "field": "n_ratings", "label": "", "value": summary.get("n_ratings")},
        {"section": "overall", "field": "n_items", "label": "", "value": summary.get("n_items")},
        {"section": "overall", "field": "n_raters", "label": "", "value": summary.get("n_raters")},
    ]
    for field, counts in summary.get("label_counts", {}).items():
        for label, value in counts.items():
            rows.append({"section": "label_counts", "field": field, "label": label, "value": value})
    for field, agreement in summary.get("rater_agreement", {}).items():
        for label, value in agreement.items():
            rows.append({"section": "rater_agreement", "field": field, "label": label, "value": value})
    for reason, count in summary.get("primary_failure_reason_counts", {}).items():
        rows.append({"section": "failure_reasons", "field": "primary_failure_reason", "label": reason, "value": count})
    return rows


def build_paper_artifacts(
    *,
    root: Path,
    baseline_run_id: str,
    out_dir: Path,
    remediation_run_id: str | None = None,
    frontier_run_id: str | None = None,
    ablation_run_ids: list[str] | None = None,
    stress_baseline_run_id: str | None = None,
    stress_remediation_run_id: str | None = None,
    regression_gate_summary_path: Path | None = None,
) -> dict[str, Any]:
    out_dir.mkdir(parents=True, exist_ok=True)
    tables_dir = out_dir / "tables"
    baseline_root = root / "runs" / baseline_run_id
    baseline_analysis = read_json(baseline_root / "v2" / "analysis.json")
    if not baseline_analysis:
        raise FileNotFoundError(f"missing baseline v2 analysis: {baseline_root / 'v2' / 'analysis.json'}")

    _write_csv(tables_dir / "baseline_overall.csv", _overall_rows(baseline_analysis, baseline_run_id))
    _write_csv(tables_dir / "baseline_refusal_by_model.csv", _metric_rows(baseline_analysis.get("refusal", {}).get("by_model", {}), "model"))
    _write_csv(tables_dir / "baseline_refusal_by_role.csv", _metric_rows(baseline_analysis.get("refusal", {}).get("by_role", {}), "role"))
    _write_csv(tables_dir / "baseline_quality_by_role.csv", _metric_rows(baseline_analysis.get("quality_non_refusal", {}).get("by_role", {}), "role"))
    _write_csv(tables_dir / "baseline_profile_by_role.csv", _metric_rows(baseline_analysis.get("role_profile", {}).get("by_role", {}), "role"))
    _write_csv(tables_dir / "baseline_profile_mismatches.csv", baseline_analysis.get("role_profile", {}).get("top_profile_mismatches", []))

    comparison_paths = sorted((baseline_root / "v2").glob("comparison_*.json"))
    robustness = read_json(comparison_paths[0]) if comparison_paths else {}
    if robustness:
        _write_csv(
            tables_dir / "judge_robustness_by_model.csv",
            _metric_rows(robustness.get("by_model", {}), "model"),
        )
        _write_csv(tables_dir / "judge_disagreement_examples.csv", robustness.get("top_disagreements", [])[:20])

    frontier_summary = {}
    if frontier_run_id:
        frontier_root = root / "runs" / frontier_run_id
        frontier_analysis = read_json(frontier_root / "v2" / "analysis.json")
        if frontier_analysis:
            frontier_summary = {
                "run_id": frontier_run_id,
                "overall": frontier_analysis.get("overall", {}),
                "exploratory_same_provider": frontier_analysis.get("exploratory_same_provider"),
            }
            _write_csv(tables_dir / "frontier_overall.csv", _overall_rows(frontier_analysis, frontier_run_id))

    remediation_summary = {"available": False, "run_id": remediation_run_id}
    if remediation_run_id:
        remediation_root = root / "runs" / remediation_run_id
        remediation_analysis = read_json(remediation_root / "v2" / "analysis.json")
        baseline_scores = _load_primary_scores(baseline_root)
        remediation_scores = _load_primary_scores(remediation_root)
        if remediation_analysis and baseline_scores and remediation_scores:
            delta_rows = matched_remediation_deltas(baseline_scores, remediation_scores)
            if _has_delta_observations(delta_rows):
                _write_csv(tables_dir / "remediation_matched_deltas.csv", delta_rows)
                _write_csv(tables_dir / "remediation_overall.csv", _overall_rows(remediation_analysis, remediation_run_id))
                remediation_summary = {
                    "available": True,
                    "run_id": remediation_run_id,
                    "overall": remediation_analysis.get("overall", {}),
                    "matched_delta_rows": len(delta_rows),
                }
        else:
            (out_dir / "remediation_status.md").write_text(
                "\n".join(
                    [
                        "# Remediation Status",
                        "",
                        f"Run `{remediation_run_id}` is configured but does not yet have complete v2 analysis and primary scores.",
                        "After running the remediation arm, rerun `build-paper-artifacts` to populate `tables/remediation_matched_deltas.csv`.",
                    ]
                )
                + "\n",
                encoding="utf-8",
            )

    baseline_scores = _load_primary_scores(baseline_root)
    ablation_rows: list[dict[str, Any]] = []
    ablation_available: list[str] = []
    for ablation_run_id in ablation_run_ids or []:
        ablation_root = root / "runs" / ablation_run_id
        ablation_scores = _load_primary_scores(ablation_root)
        if not baseline_scores or not ablation_scores:
            continue
        rows = _delta_rows_with_arm(baseline_scores, ablation_scores, arm=ablation_run_id)
        if _has_delta_observations(rows):
            ablation_rows.extend(rows)
            ablation_available.append(ablation_run_id)
    if ablation_rows:
        _write_csv(
            tables_dir / "policy_ablation_deltas.csv",
            ablation_rows,
            fieldnames=["arm", "slice", "metric", "n", "mean_delta", "ci95_low", "ci95_high"],
        )
    else:
        _write_csv(
            tables_dir / "policy_ablation_deltas.csv",
            [],
            fieldnames=["arm", "slice", "metric", "n", "mean_delta", "ci95_low", "ci95_high"],
        )

    stress_summary = {
        "available": False,
        "baseline_run_id": stress_baseline_run_id,
        "remediation_run_id": stress_remediation_run_id,
    }
    if stress_baseline_run_id and stress_remediation_run_id:
        stress_baseline_root = root / "runs" / stress_baseline_run_id
        stress_remediation_root = root / "runs" / stress_remediation_run_id
        stress_baseline_scores = _load_primary_scores(stress_baseline_root)
        stress_remediation_scores = _load_primary_scores(stress_remediation_root)
        stress_rows = (
            matched_remediation_deltas(stress_baseline_scores, stress_remediation_scores)
            if stress_baseline_scores and stress_remediation_scores
            else []
        )
        if _has_delta_observations(stress_rows):
            _write_csv(tables_dir / "stress_matched_deltas.csv", stress_rows)
            stress_summary = {
                "available": True,
                "baseline_run_id": stress_baseline_run_id,
                "remediation_run_id": stress_remediation_run_id,
                "matched_delta_rows": len(stress_rows),
            }
        else:
            _write_csv(tables_dir / "stress_matched_deltas.csv", [], fieldnames=["slice", "metric", "n", "mean_delta", "ci95_low", "ci95_high"])

    regression_summary = {
        "available": False,
        "path": _display_path(regression_gate_summary_path, root) if regression_gate_summary_path else None,
    }
    if regression_gate_summary_path:
        gate_result = read_json(regression_gate_summary_path)
        if gate_result:
            regression_rows = _flatten_regression_gate(gate_result)
            _write_csv(tables_dir / "regression_gate_summary.csv", regression_rows, fieldnames=["metric", "value"])
            regression_summary = {
                "available": True,
                "path": _display_path(regression_gate_summary_path, root),
                "passed": gate_result.get("passed"),
                "failures": gate_result.get("failures", []),
                "n_common": gate_result.get("n_common"),
            }
        else:
            _write_csv(tables_dir / "regression_gate_summary.csv", [], fieldnames=["metric", "value"])

    human_summary = read_json(baseline_root / "v2" / "human_rating_summary.json")
    human_calibration_summary = {
        "available": bool(human_summary),
        "n_ratings": human_summary.get("n_ratings"),
        "n_items": human_summary.get("n_items"),
        "n_raters": human_summary.get("n_raters"),
    }
    _write_csv(
        tables_dir / "human_rating_summary.csv",
        _human_summary_rows(human_summary),
        fieldnames=["section", "field", "label", "value"],
    )

    summary = {
        "schema": "adfe_neurips_workshop_artifacts.v1",
        "baseline_run_id": baseline_run_id,
        "baseline": {
            "overall": baseline_analysis.get("overall", {}),
            "paired_refusal": baseline_analysis.get("refusal", {}).get("paired_parity", {}),
            "judge_model": baseline_analysis.get("judge_model"),
        },
        "judge_robustness": {
            "available": bool(robustness),
            "n_common": robustness.get("n_common"),
            "refusal_agreement_rate": robustness.get("refusal_agreement_rate"),
            "poststratified": robustness.get("poststratified", {}),
        },
        "frontier": frontier_summary,
        "remediation": remediation_summary,
        "policy_ablations": {
            "available": bool(ablation_available),
            "available_run_ids": ablation_available,
            "requested_run_ids": ablation_run_ids or [],
            "n_available": len(ablation_available),
        },
        "stress": stress_summary,
        "regression_gate": regression_summary,
        "human_calibration": human_calibration_summary,
        "tables_dir": str(tables_dir.relative_to(root) if tables_dir.is_relative_to(root) else tables_dir),
    }
    write_json(out_dir / "paper_metrics.json", summary)
    _write_numbers_tex(out_dir / "numbers.tex", summary)
    return summary
